/* Generated By:JavaCC: Do not edit this line. DenotexParserConstants.java */
package org.rubato.rubettes.denotex;

public interface DenotexParserConstants {

  int EOF = 0;
  int INTEGER_LITERAL = 7;
  int FLOATING_POINT_LITERAL = 8;
  int EXPONENT = 9;
  int STRING_LITERAL = 10;
  int INCLUDE = 11;
  int BEGIN = 12;
  int END = 13;
  int FORM = 14;
  int SUBSTANCE = 15;
  int MODULE = 16;
  int NAMESPACE = 17;
  int SYN_O = 18;
  int SYN_C = 19;
  int LIST_O = 20;
  int LIST_C = 21;
  int IDENTIFIER = 22;
  int QIDENTIFIER = 23;
  int LETTER = 24;
  int DIGIT = 25;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<INTEGER_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "\"#include\"",
    "\"&begin\"",
    "\"&end\"",
    "\"form\"",
    "\"substance\"",
    "\"module\"",
    "\"namespace\"",
    "\"<|\"",
    "\"|>\"",
    "\"<<\"",
    "\">>\"",
    "<IDENTIFIER>",
    "<QIDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "\"/\"",
    "\":\"",
    "\".\"",
    "\"[\"",
    "\"]\"",
    "\"<\"",
    "\">\"",
    "\"{\"",
    "\"}\"",
    "\"@\"",
    "\"_\"",
    "\"^\"",
    "\"+\"",
    "\"-\"",
    "\"i\"",
    "\"*\"",
  };

}
